#!/bin/sh

# xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
setbg &		# set background with `setbg` script, modified from Luke Smith's voidrice
dwmblocks &

xcompmgr &

[ -n "$xrdbpid" ] && wait "$xrdbpid"
