#!/bin/sh

# xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
setbg &		# set background with `setbg` script, modified from Luke Smith's voidrice
dwmblocks &

xcompmgr &

# Setting capslock to control on hold and escape on press and release (within 200ms)
setxkbmap us -option 'caps:ctrl_modifier' && xcape -t 200 -e 'Caps_Lock=Escape' &

[ -n "$xrdbpid" ] && wait "$xrdbpid"
